# Generated by Django 5.2.6 on 2026-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
